name: Expand template
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
    push:
        branches:
            - main
    workflow_dispatch:
        inputs:
            test-mode:
                description: "Test mode"
                required: true
                default: "normal"
                type: choice
                options:
                    - none
                    - normal
                    - strict

concurrency:
    group: expand-${{ github.ref_name }}
    cancel-in-progress: true

jobs:
    replace:
        runs-on: ${{ vars.RUNNER_IMAGE }}

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref || github.ref_name }}
                  fetch-depth: 0
                  ssh-key: ${{ secrets.SSH_KEY }}

            - name: Use ccache
              uses: hendrikmuhs/ccache-action@v1.2
              with:
                  create-symlink: true

            - name: Cache installation
              id: cache-lib
              if: ${{ github.event.inputs.test-mode != 'strict' }}
              uses: actions/cache@v4
              env:
                cache-name: cache-install
              with:
                save-always: true
                path: |
                  /tmp/ac_install/
                  /opt/
                key: build-${{ hashFiles('./src/**') }}
                restore-keys: |
                  build-

            - name: Expand template
              env:
                  RUN_TEST: ${{ github.event.inputs.test-mode == 'strict' }}
              run: ./.github/workflows/internal/expand.sh

            - name: Test
              if: ${{ github.event.inputs.test-mode != 'none' }}
              run: ./.github/workflows/internal/test.sh

            - name: Lint
              run: ./.github/workflows/internal/lint.sh

            - name: Push
              if: ${{ !cancelled() && github.ref_name == 'main' }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  set -eu

                  git remote set-url origin git@github.com:${GITHUB_REPOSITORY}.git

                  git config --global user.name "Template Expander"
                  git config --global user.email "noreply@example.com"

                  git add -f ./dist/

                  if (git diff --cached --shortstat | grep '[0-9]'); then
                    git commit -m "[workflow] expand templates ${GITHUB_SHA}"

                    REPOSITORY_NAME="${{ github.head_ref || github.ref_name }}"

                    git pull --rebase origin "${REPOSITORY_NAME}"
                    git push origin "HEAD:${REPOSITORY_NAME}"
                  else
                    echo "No updated files."
                  fi
